// Import necessary dependencies and styles
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Configure the Poppins font with specific weights and display settings
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-poppins",
});

// Define metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component: This layout will be applied to all pages
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Set the language for the entire application
    <html lang="en">
      {/* Apply the Poppins font variable and sans-serif font family to the body */}
      <body className={`${poppins.variable} font-sans`}>
        {/* Render the child components (page content) within the layout */}
        {children}
      </body>
    </html>
  );
}
